# Build stage
FROM maven:3.8.6-openjdk-8-slim AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Runtime stage
FROM openjdk:8-jre-slim
WORKDIR /app
COPY --from=build /app/target/MS-specialite-0.0.1-SNAPSHOT.jar specialite-img.jar
EXPOSE 8083

ENTRYPOINT ["java", "-jar", "specialite-img.jar"]