version: "3.9"
services:
  universite:
    build: .\Universite
    image: "universite-img"
    container_name: universite
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/universite?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    networks:
      - unihub-network
    depends_on:
      - eureka
      - mysql-db

  restaurant:
    build: .\restaurant
    image: "restaurant-img"
    container_name: restaurant
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
    restart: unless-stopped
    networks:
      - unihub-network
    depends_on:
      - eureka

  
  event:
    build: .\Event_MS
    image: "event-img"
    container_name: event
    ports:
      - "8087:8087"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/event?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    networks:
      - unihub-network
    depends_on:
      - eureka
      - mysql-db

  specialite:
    build: .\MS_specialite
    image: "specialite-img"
    container_name: specialite
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/MS-Specialite?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    networks:
      - unihub-network
    depends_on:
      - eureka
      - mysql-db

  news:
    build: .\UniHub-news
    image: news
    container_name: news
    ports:
      - "8085:8085"
    volumes:
      - ./upload-directory:/upload-directory
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/unihub_news?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - APP_FILE_UPLOAD_DIR=/upload-directory
    restart: unless-stopped
    networks:
      - unihub-network
    depends_on:
      - eureka
      - mysql-db

  eureka:
    build: .\EurekaD
    image: "eureka-img"
    container_name: "eureka"
    ports:
      - "8761:8761"
    hostname: discovery
    networks:
      - unihub-network

  gateway:
    build: .\ApiGateway
    image: "gateway-img"
    container_name: "gateway"
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
      - spring_cloud_gateway_routes[0]_id=universite
      - spring_cloud_gateway_routes[0]_uri=http://universite:8084
      - spring_cloud_gateway_routes[0]_predicates[0]=Path=/universite/**

      - spring_cloud_gateway_routes[1]_id=specialite
      - spring_cloud_gateway_routes[1]_uri=http://specialite:8083
      - spring_cloud_gateway_routes[1]_predicates[0]=Path=/specialites/**

      - spring_cloud_gateway_routes[2]_id=event
      - spring_cloud_gateway_routes[2]_uri=http://event:8087
      - spring_cloud_gateway_routes[2]_predicates[0]=Path=/event/**

      - spring_cloud_gateway_routes[3]_id=restaurant
      - spring_cloud_gateway_routes[3]_uri=http://restaurant:8090
      - spring_cloud_gateway_routes[3]_predicates[0]=Path=/restaurants/**

      - spring_cloud_gateway_routes[4]_id=news
      - spring_cloud_gateway_routes[4]_uri=http://news:8085
      - spring_cloud_gateway_routes[4]_predicates[0]=Path=/news/**

      - spring_cloud_gateway_routes[5]_id=static-resources
      - spring_cloud_gateway_routes[5]_uri=http://news:8085
      - spring_cloud_gateway_routes[5]_predicates[0]=Path=/upload-directory/**
      - spring_cloud_gateway_routes[5]_filters[0]=AddResponseHeader=Access-Control-Allow-Origin,*
      - spring_cloud_gateway_routes[5]_filters[1]=AddResponseHeader=Access-Control-Allow-Methods,GET,POST,OPTIONS

    networks:
      - unihub-network
    depends_on:
      - eureka
      - universite
      - event
      - news
      - restaurant
      - specialite

  mysql-db:
    image: "mysql:5.6"
    container_name: "mysql-db"
    environment:
      - MYSQL_ROOT_PASSWORD=root #indisponsable pour la conteneurisation
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - unihub-network

# Define a custom network with a specific name
networks:
  unihub-network:
    name: unihub-network

